server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: hiberus-bank-bizum
  datasource:
    url: jdbc:mysql://${hiberus-bank-bizum-db:localhost}:3306/hiberus-bank-bizum-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: hiberus-bank-bizum
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
